name: Release Version
on:
  push:
#    tags:
#      - "v*.*.*"

env:
  MATE_DESKTOP_VERSION: 1.28.2
  CACHE_PATH: /tmp/.cache

jobs:
  release:
    name: Release New Version
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Dump env
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
#      - name: Install dependency packages
#        run: sudo .github/workflows/ubuntu.sh
#
#      - name: Install higher version Mate component packages
#        run: sudo .github/workflows/mate-desktop.sh ${{env.MATE_DESKTOP_VERSION}} ${{ env.CACHE_PATH }}
#
#      - name: Build the source code
#        run: .github/workflows/builds.sh
#
#      - name: Install GH CLI
#        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
#        with:
#          gh-cli-version: 2.39.1
#
#      - name: Create github release
#        run: |
#          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes _build/meson-dist/*
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
